stages:
  load_data:
    cmd: python src/load_data.py --config=params.yaml
    deps:
    - src/get_data.py
    - src/load_data.py
    - data_given/sample.csv
    outs:
    - data/raw/sample.csv

  split_data:
    cmd: python src/split_data.py --config=params.yaml
    deps:
    - src/get_data.py
    - data/raw/sample.csv
    outs:
    - data/processed/train_sample.csv
    - data/processed/test_sample.csv

  model:
    cmd: python src/train_eval.py --config=params.yaml
    deps:
    - src/train_eval.py
    - data/processed/train_sample.csv
    - data/processed/test_sample.csv
    params:
    - estimators.ElasticNet.params.alpha
    - estimators.ElasticNet.params.l1_ratio
    metrics:
    - report/scores.json:
        cache: false
    - report/params.json:
        cache: false
    outs:
    - saved_models/lr.sav