base:
  project: sales_lr_project
  random_state: 42
  target_col: sales

data_source:
  s3_source: data_given/sample.csv

load_data:
  raw_dataset_csv: data/raw/sample.csv

split_data:
  train_path: data/processed/train_sample.csv
  test_path: data/processed/test_sample.csv
  test_size: 0.2

estimators:
  ElasticNet:
    params:
      alpha: 0.88
      l1_ratio: 0.89

model_dir: saved_models